---
# vars file for roles/apache
apache_package: "{{ 'apache2' if ansible_os_family =='Debian' else 'httpd' }}"
apache_service: "{{ 'apache2' if ansible_os_family =='Debian' else 'httpd' }}"
root_group: "{{ 'root' if ansible_os_family =='Debian' else 'wheel' }}"
